services:
  postgresql:
    image: postgres:latest
    container_name: parking-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: parking-database-pwd-123
      POSTGRES_DB: db-parking

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: parking-pdadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgresql
