name: ASP.NET 8 Build

on:
  push:
    branches:
      - "main**"
      - "develop**"

jobs:
  Build_And_Test:
    name: Build and Run Unit Tests with Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Install Coverlet Global Tool
        run: dotnet tool install --global coverlet.console

      - name: Test and Get Code Coverage
        run: coverlet /UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --targetargs "test ./UnitTests/UnitTests.csproj --no-build"
